"""
ping.logging
============

Writes structured, reproducible experiment session records.

Why metadata is a separate JSON file per run, rather than embedding
everything in data/EXPERIMENT_LOG.md:
FR-018 requires "data logging with metadata" for every experiment. A
markdown table is good for a human scanning session history, but a poor
place to store a full configuration snapshot - it invites hand-editing,
which breaks reproducibility (PRDS Section 7.1). Instead, every session
gets its own timestamped JSON file recording exactly which PINGConfig was
used, so any past run can be reproduced or audited independently of the
log. data/EXPERIMENT_LOG.md remains a lightweight, append-only index that
links to those files.

Why append-only:
Each call to log_experiment_session() adds a new row; existing rows
(including the "Planned" placeholders each experiment starts with) are
never modified or removed. This preserves full session history, including
failed or superseded runs, consistent with PRDS Section 8.4: "negative
results are part of the scientific record."

Status labels are plain, all-uppercase text (PLANNED, IN PROGRESS, PASS,
WARN, FAIL) - not emoji - by Project Lead decision, for grep-ability and
to avoid any dependency on emoji rendering/encoding across platforms.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from ping.config import PINGConfig

# Status values and their display labels. All-uppercase, plain text - no
# emoji - so that (a) grep/search across the log is trivial, (b) status
# stands out visually in the table without relying on font/terminal emoji
# rendering support, and (c) no explicit UTF-8 handling is required just
# to read this file back on any platform. Any status outside this set is
# rejected - same "fail loud on bad input" philosophy as ping.config.
#
# Note: this deviates from the emoji legend originally shown in PRDS
# Section 9.2 (Project Lead decision - PRDS to be updated to match).
STATUS_LABELS: dict[str, str] = {
    "PLANNED": "PLANNED",
    "IN_PROGRESS": "IN PROGRESS",
    "PASS": "PASS",
    "WARN": "WARN",
    "FAIL": "FAIL",
}

DEFAULT_LOG_PATH = Path("data/EXPERIMENT_LOG.md")
DEFAULT_METADATA_DIR = Path("data/logs")

# Markdown table header this module expects to find (and will create if
# the log file does not yet exist). Matches the format already in use in
# the repository's data/EXPERIMENT_LOG.md.
_LOG_HEADER = "| ID | Date | Status | Notes |\n|----|------|--------|-------|\n"


class ExperimentLogError(ValueError):
    """Raised when an experiment session cannot be logged - e.g. an
    unrecognized status string, or an experiment_id that doesn't match
    the PING ID format (EXP-###).
    """


@dataclass(frozen=True)
class ExperimentSession:
    """A single, immutable record of one experiment run.

    Attributes:
        experiment_id: e.g. "EXP-001". Must match PRDS Section 8.1 IDs.
        title: Short human-readable title, e.g. "Multichannel Synchronization".
        status: One of STATUS_LABELS keys (PLANNED, IN_PROGRESS, PASS, WARN, FAIL).
        timestamp: UTC timestamp of when this session was logged.
        config: The full PINGConfig used for this run, for reproducibility.
        notes: Free-text summary (e.g. "timing offset 0.3 samples, within FR-001").
        results_path: Optional path to figures/report generated by this run.
    """

    experiment_id: str
    title: str
    status: str
    timestamp: datetime
    config: PINGConfig
    notes: str = ""
    results_path: Optional[str] = None

    def __post_init__(self) -> None:
        if self.status not in STATUS_LABELS:
            raise ExperimentLogError(
                f"status='{self.status}' is not one of "
                f"{sorted(STATUS_LABELS)}."
            )
        if not self.experiment_id.startswith("EXP-"):
            raise ExperimentLogError(
                f"experiment_id='{self.experiment_id}' does not match the "
                "PRDS Section 8.1 EXP-### convention."
            )

    def to_metadata_dict(self) -> dict:
        """Serializes this session to a JSON-safe dict, including a full
        snapshot of the config used, so the run can be reproduced or
        audited independently of the log.md summary row.
        """
        return {
            "experiment_id": self.experiment_id,
            "title": self.title,
            "status": self.status,
            "timestamp": self.timestamp.isoformat(),
            "notes": self.notes,
            "results_path": self.results_path,
            "config": asdict(self.config),
        }


def _metadata_filename(session: ExperimentSession) -> str:
    """Builds a unique, sortable filename for one session's metadata file.

    Timestamp is embedded (second resolution) so filenames sort
    chronologically at a glance. A short random suffix is also appended -
    two sessions logged within the same wall-clock second (e.g. rapid
    repeated CLAP attempts, or parallel test runs) would otherwise produce
    the *identical* filename and silently overwrite each other's metadata.
    """
    ts = session.timestamp.strftime("%Y%m%dT%H%M%S")
    unique_suffix = uuid.uuid4().hex[:8]
    return f"{session.experiment_id}_{ts}_{unique_suffix}.json"


def _write_metadata_file(session: ExperimentSession, metadata_dir: Path) -> Path:
    """Writes the session's full metadata (including config snapshot) to
    its own JSON file. Returns the path written, so the caller can link
    to it from the markdown log.
    """
    metadata_dir.mkdir(parents=True, exist_ok=True)
    metadata_path = metadata_dir / _metadata_filename(session)

    with metadata_path.open("w", encoding="utf-8") as f:
        json.dump(session.to_metadata_dict(), f, indent=2)

    return metadata_path


def _append_log_row(
    session: ExperimentSession, metadata_path: Path, log_path: Path
) -> None:
    """Appends one row to data/EXPERIMENT_LOG.md linking to the metadata
    file. Creates the file with the standard header if it does not exist
    yet. Never rewrites or removes existing rows.
    """
    log_path.parent.mkdir(parents=True, exist_ok=True)

    if not log_path.exists():
        log_path.write_text(_LOG_HEADER, encoding="utf-8")

    # Link is relative to the log file's own directory, so the log stays
    # portable if the repository is moved or cloned elsewhere.
    try:
        relative_metadata_path = metadata_path.relative_to(log_path.parent)
    except ValueError:
        relative_metadata_path = metadata_path

    date_str = session.timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")
    status_str = STATUS_LABELS[session.status]
    notes_str = session.notes.replace("|", "\\|")  # escape pipes: would break the table
    link = f"[metadata]({relative_metadata_path.as_posix()})"
    notes_cell = f"{link} - {notes_str}" if notes_str else link

    row = f"| {session.experiment_id} | {date_str} | {status_str} | {notes_cell} |\n"

    with log_path.open("a", encoding="utf-8") as f:
        f.write(row)


def log_experiment_session(
    experiment_id: str,
    title: str,
    status: str,
    config: PINGConfig,
    notes: str = "",
    results_path: Optional[str] = None,
    log_path: Path | str = DEFAULT_LOG_PATH,
    metadata_dir: Path | str = DEFAULT_METADATA_DIR,
) -> Path:
    """Records one experiment session: writes a timestamped JSON metadata
    file, then appends a linking row to data/EXPERIMENT_LOG.md.

    This is the single entry point every experiment script should call at
    the end of a run (PRDS Section 5.4, Layer 4: "ping.logging saves raw
    audio, metadata, and figures").

    Args:
        experiment_id: e.g. "EXP-001".
        title: Short human-readable title matching PRDS Section 8.1.
        status: One of "PLANNED", "IN_PROGRESS", "PASS", "WARN", "FAIL".
        config: The PINGConfig used for this run.
        notes: Free-text summary of the outcome.
        results_path: Optional path to generated figures/report.
        log_path: Path to the markdown log file (default: data/EXPERIMENT_LOG.md).
        metadata_dir: Directory for per-session JSON files (default: data/logs).

    Returns:
        Path to the JSON metadata file written for this session.

    Raises:
        ExperimentLogError: If status is invalid or experiment_id does not
            match the EXP-### convention.
    """
    session = ExperimentSession(
        experiment_id=experiment_id,
        title=title,
        status=status,
        timestamp=datetime.now(timezone.utc),
        config=config,
        notes=notes,
        results_path=results_path,
    )

    metadata_path = _write_metadata_file(session, Path(metadata_dir))
    _append_log_row(session, metadata_path, Path(log_path))

    return metadata_path